name: Merge latest-charts againt master
on:
  workflow_run:
    workflows: ["Opensource Charts Validation"]
    types:
      - completed

jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
